#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

#sxhkd -c ~/.config/sxhkd/sxhkdrc &

bspc monitor -d 1 2 3 4 5
bspc config window_gap      10
bspc config split_ratio     0
bspc config focus_follows_pointer   true
bspc config borderless_monocle true
bspc config single_monocle true
bspconfig gapless_monocle   true
bspc config automatic_scheme    spiral

killall picom
#picom --blur-background --corner-radius 10 --backend glx &
picom --blur-background --corner-radius 18 --backend glx
killall polybar
polybar left &
polybar center &
polybar right &
killall polybar
polybar main & 
killall feh
#feh --bg-center ~/Pictures/Wallpapers/marita-kavelashvili-ugnrXk1129g-unsplash.jpg
feh --bg-scale ~/Pictures/Wallpapers/blobs.svg &
#feh --bg-scale ~/Pictures/Wallpapers/background.jpg
