#!/bin/bash

STATUS="$(systemctl is-active openvpn-client@imc.service)"
if [ "${STATUS}" = "inactive" ]; then
  if [ $1 = 'toggle' ]; then
    systemctl start openvpn-client@imc.service
    text="{\"text\":\"󱠽 \",\"class\":\"enabled\"}"
  fi
  text="{\"text\":\"󱠾\",\"tooltip\":\"imc closed\"}"
else
  if [ $1 = 'toggle' ]; then
    systemctl stop openvpn-client@imc.service
    text="{\"text\":\"󱠾\",\"tooltip\":\"imc closed\"}"
  fi
  ADDR="$(ip -br addr show dev tun0 | awk '{ print $3 }')"
  text="{\"text\":\"󱠽 \",\"class\":\"enabled\",\"tooltip\":\"$ADDR\"}"
fi
echo $text
