[colors.bright]
black = "0x737475"
blue = "0x3182bd"
cyan = "0x80b1d3"
green = "0x31a354"
magenta = "0x756bb1"
red = "0xe31a1c"
white = "0xfcfdfe"
yellow = "0xdca060"

[colors.normal]
black = "0x0c0d0e"
blue = "0x3182bd"
cyan = "0x80b1d3"
green = "0x31a354"
magenta = "0x756bb1"
red = "0xe31a1c"
white = "0xb7b8b9"
yellow = "0xdca060"

[colors.primary]
background = "0x0c0d0e"
foreground = "0xb7b8b9"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 14.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[window]
decorations = "Full"
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[shell]
program = "/bin/zsh"
